/**
 * WASABI Print Utilities
 *
 * Helpers for generating print-friendly views of student data
 */

interface PrintOptions {
  title?: string;
  subtitle?: string;
  showDate?: boolean;
  orientation?: 'portrait' | 'landscape';
}

/**
 * Open a new window with print-friendly content
 */
export function printContent(content: string, options: PrintOptions = {}): void {
  const {
    title = 'WASABI Report',
    subtitle,
    showDate = true,
    orientation = 'portrait',
  } = options;

  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Please allow popups to print reports');
    return;
  }

  const dateStr = showDate ? new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  }) : '';

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>${title}</title>
      <style>
        @page {
          size: ${orientation};
          margin: 1in;
        }

        * {
          box-sizing: border-box;
          margin: 0;
          padding: 0;
        }

        body {
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
          font-size: 12pt;
          line-height: 1.5;
          color: #1f2937;
          padding: 0.5in;
        }

        .header {
          text-align: center;
          margin-bottom: 1.5em;
          padding-bottom: 1em;
          border-bottom: 2px solid #84cc16;
        }

        .header h1 {
          font-size: 24pt;
          color: #1f2937;
          margin-bottom: 0.25em;
        }

        .header .subtitle {
          font-size: 14pt;
          color: #4b5563;
        }

        .header .date {
          font-size: 10pt;
          color: #6b7280;
          margin-top: 0.5em;
        }

        .content {
          margin-top: 1em;
        }

        table {
          width: 100%;
          border-collapse: collapse;
          margin: 1em 0;
        }

        th, td {
          border: 1px solid #d1d5db;
          padding: 8px 12px;
          text-align: left;
        }

        th {
          background-color: #f3f4f6;
          font-weight: 600;
        }

        tr:nth-child(even) {
          background-color: #f9fafb;
        }

        .section {
          margin: 1.5em 0;
        }

        .section-title {
          font-size: 14pt;
          font-weight: 600;
          color: #374151;
          margin-bottom: 0.5em;
          padding-bottom: 0.25em;
          border-bottom: 1px solid #e5e7eb;
        }

        .stat-grid {
          display: grid;
          grid-template-columns: repeat(3, 1fr);
          gap: 1em;
          margin: 1em 0;
        }

        .stat-card {
          background: #f9fafb;
          border: 1px solid #e5e7eb;
          border-radius: 8px;
          padding: 1em;
          text-align: center;
        }

        .stat-value {
          font-size: 24pt;
          font-weight: 700;
          color: #84cc16;
        }

        .stat-label {
          font-size: 10pt;
          color: #6b7280;
        }

        .footer {
          margin-top: 2em;
          padding-top: 1em;
          border-top: 1px solid #e5e7eb;
          text-align: center;
          font-size: 9pt;
          color: #9ca3af;
        }

        .page-break {
          page-break-before: always;
        }

        @media print {
          body {
            padding: 0;
          }

          .no-print {
            display: none;
          }
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>${title}</h1>
        ${subtitle ? `<div class="subtitle">${subtitle}</div>` : ''}
        ${showDate ? `<div class="date">${dateStr}</div>` : ''}
      </div>

      <div class="content">
        ${content}
      </div>

      <div class="footer">
        Generated by WASABI - Wide Array Student Analytics and Benchmarking Interface
      </div>

      <script>
        window.onload = function() {
          window.print();
        }
      </script>
    </body>
    </html>
  `);

  printWindow.document.close();
}

/**
 * Generate HTML table from data
 */
export function generateTable(
  data: Record<string, any>[],
  columns: { key: string; label: string }[]
): string {
  if (data.length === 0) return '<p>No data available</p>';

  const headerRow = columns.map(col => `<th>${col.label}</th>`).join('');
  const bodyRows = data.map(row =>
    `<tr>${columns.map(col => `<td>${row[col.key] ?? '-'}</td>`).join('')}</tr>`
  ).join('');

  return `
    <table>
      <thead><tr>${headerRow}</tr></thead>
      <tbody>${bodyRows}</tbody>
    </table>
  `;
}

/**
 * Generate stat cards grid
 */
export function generateStatCards(
  stats: { label: string; value: string | number }[]
): string {
  return `
    <div class="stat-grid">
      ${stats.map(stat => `
        <div class="stat-card">
          <div class="stat-value">${stat.value}</div>
          <div class="stat-label">${stat.label}</div>
        </div>
      `).join('')}
    </div>
  `;
}

/**
 * Generate a section with title and content
 */
export function generateSection(title: string, content: string): string {
  return `
    <div class="section">
      <div class="section-title">${title}</div>
      ${content}
    </div>
  `;
}

/**
 * Add a page break for multi-page reports
 */
export function pageBreak(): string {
  return '<div class="page-break"></div>';
}
